define({
  images: {
    'background'         : 'resources/images/background.png'
  , 'ball'               : 'resources/images/ball.png'
  , 'brick-color-1'      : 'resources/images/brick-color-1.png'
  , 'brick-color-2'      : 'resources/images/brick-color-2.png'
  , 'brick-color-3'      : 'resources/images/brick-color-3.png'
  , 'brick-color-4'      : 'resources/images/brick-color-4.png'
  , 'brick-color-5'      : 'resources/images/brick-color-5.png'
  , 'brick-fallthrough'  : 'resources/images/brick-fallthrough.png'
  , 'brick-solid-0'      : 'resources/images/brick-solid-0.png'
  , 'brick-solid-1'      : 'resources/images/brick-solid-1.png'
  , 'brick-solid-2'      : 'resources/images/brick-solid-2.png'
  , 'brick-solid-3'      : 'resources/images/brick-solid-3.png'
  , 'brick-solid-4'      : 'resources/images/brick-solid-4.png'
  , 'dot'                : 'resources/images/dot.png'
  , 'effect-flicker'     : 'resources/images/effect-flicker.png'
  , 'line'               : 'resources/images/line.png'
  , 'pad'                : 'resources/images/pad.png'
  , 'pad-area'           : 'resources/images/pad-area.png'
  , 'shadow-ball'        : 'resources/images/shadow-ball.png'
  , 'shadow-brick-0'     : 'resources/images/shadow-brick-0.png'
  , 'shadow-brick-1'     : 'resources/images/shadow-brick-1.png'
  , 'shadow-brick-2'     : 'resources/images/shadow-brick-2.png'
  , 'shadow-brick-3'     : 'resources/images/shadow-brick-3.png'
  , 'shadow-brick-4'     : 'resources/images/shadow-brick-4.png'
  , 'shadow-fallthrough' : 'resources/images/shadow-fallthrough.png'
  , 'shadow-pad'         : 'resources/images/shadow-pad.png'
  }
})